wells: []

controls:
  - initial_guess: 0.25
    max: 1.0
    min: -1.0
    name: point
    perturbation_magnitude: 0.005
    type: generic_control
    variables:
      - name: x
        index: 0
      - name: x
        index: 1
      - name: x
        index: 2

objective_functions:
  - name: distance

input_constraints:
  - weights:
      point.x.0: 0
      point.x.1: 0
      point.x.2: 1
    upper_bound: 0.4

output_constraints:
  - name: x-0_coord
    lower_bound: 0.1

# Optimal value expected at x=0.1, y=0, z=0.4, with distance 3.72

install_jobs:
  - name: adv_distance3
    executable: jobs/adv_distance3.py
  - name: adv_dump_controls
    executable: jobs/adv_dump_controls.py

forward_model:
  - adv_distance3     --point-file point.json
    --target-file data/r{{ realization}}/target.json
    --out distance
  - adv_dump_controls --controls-file point.json
    --out-suffix _coord

model:
  realizations: [0, 2]
  realizations_weights: [0.25, 0.75]

install_data:
  - link: false
    source: r{{ configpath }}/adv_target_r{{ realization }}.json
    target: data/r{{ realization}}/target.json

optimization:
  algorithm: SLSQP
  convergence_tolerance: 0.0001
  speculative: True
  max_batch_num: 2

environment:
  random_seed: 123
  output_folder: everest_output/
