controls:
  - max: 2
    min: -2
    name: point
    perturbation_magnitude: 1e-6
    type: generic_control
    # auto_scale: True
    variables:
      - name: x
        index: 1
        initial_guess: 0.8
      - name: x
        index: 2
        initial_guess: 1.2
      - name: x
        index: 3
        initial_guess: 1.1
      - name: x
        index: 4
        initial_guess: 0.9

objective_functions:
  - name: rosenbrock
    auto_normalize: True

install_jobs:
  - name: rosenbrock
    source: jobs/ROSENBROCK

forward_model:
  - rosenbrock \
    --vars point.json \
    --realization r{{ realization }} \
    --out rosenbrock

model:
  realizations: [0, 1, 2, 3, 4]

optimization:
  algorithm: slsqp
  perturbation_num: 5
  max_function_evaluations: 30

environment:
  log_level: debug
  random_seed: 1
  simulation_folder: simulations
  output_folder: everest_output/
